<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>lk.fujilanka.scm</groupId>
        <artifactId>GlobalSCMS</artifactId>
        <version>1.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>lk.fujilanka.scm.ear</groupId>
    <artifactId>global-scm-ear</artifactId>
    <packaging>ear</packaging>

    <dependencies>
        <dependency>
            <groupId>lk.fujilanka.scm.ejb</groupId>
            <artifactId>global-scm-ejb</artifactId>
            <type>ejb</type>
        </dependency>
        <dependency>
            <groupId>lk.fujilanka.scm.web</groupId>
            <artifactId>global-scm-web</artifactId>
            <type>war</type>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-ear-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <version>8</version>
                    <defaultLibBundleDir>lib</defaultLibBundleDir>
                    <modules>
                        <ejbModule>
                            <groupId>lk.fujilanka.scm.ejb</groupId>
                            <artifactId>global-scm-ejb</artifactId>
                            <unpack>true</unpack>
                        </ejbModule>
                        <webModule>
                            <groupId>lk.fujilanka.scm.web</groupId>
                            <artifactId>global-scm-web</artifactId>
                            <contextRoot>/global-scm</contextRoot>
                            <unpack>true</unpack>
                        </webModule>
                    </modules>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>